### ISSUE TITLE
google protobuf not work

### ISSUE THREAD

**Issue by caimaoy** [caimaoy/flask-realtime-import#1]
` import common_pb2`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "common_pb2.py", line 57, in <module>
    google.protobuf.descriptor_pb2.ServiceOptions.RegisterExtension(cmd)
  File "/Users/caimaoy/.pyenv/versions/itest-2.7.15/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 751, in RegisterExtension
    cls.DESCRIPTOR.file.pool.AddExtensionDescriptor(extension_handle)
  File "/Users/caimaoy/.pyenv/versions/itest-2.7.15/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 250, in AddExtensionDescriptor
    self._CheckConflictRegister(extension)
  File "/Users/caimaoy/.pyenv/versions/itest-2.7.15/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 153, in _CheckConflictRegister
    file_name = register[desc_name].file.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by caimaoy** [comment]
Before re-import GOOGLE_PROTOBUF_PACKAGE
You have to clear the Descriptors if it is necessary, just like below for `protobuf==3.6.1`

<https://github.com/protocolbuffers/protobuf/blob/v3.6.1/python/google/protobuf/descriptor_pool.py#L153>

```python
from google.protobuf.descriptor_pool import Default
d = Default()
d._toplevel_extensions = {}
```
